type OfflineQuestion = { id: string; value: number; prompt: string; answer: string; explanation: string; media?: { kind?: string; alt?: string; url?: string } };
type OfflineCategory = { name: string; hint?: string; questions: OfflineQuestion[] };
type OfflineGame = { title: string; topic: string; categories: OfflineCategory[]; teamNames?: string[] };

export function buildOfflineGameHtml(game: OfflineGame) {
  // A local file must never depend on a remote image host. Generated SVG data
  // URLs are self-contained and are kept; uploaded/remote images are omitted
  // from the export with the text question still fully playable.
  const offlineGame = {
    ...game,
    categories: game.categories.map((category) => ({
      ...category,
      questions: category.questions.map((question) => ({
        ...question,
        media: question.media?.url?.startsWith('data:image/') ? question.media : undefined,
      })),
    })),
  };
  const payload = JSON.stringify(offlineGame).replace(/</g, '\\u003c');

  return `<!doctype html>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>${escapeHtml(game.title)} · Offline Quiz Board</title>
  <style>
    :root{--ink:#162b45;--navy:#10223c;--board:#213f5e;--tile:#2f5a72;--lime:#c8f169;--paper:#f5f4ed;--line:rgba(200,241,105,.35)}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--navy);color:#fff;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}button{font:inherit;cursor:pointer}
    header{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:18px clamp(20px,4vw,64px);background:#0d1c31;border-bottom:1px solid rgba(255,255,255,.1)}header small{color:#c6d5df}header h1{margin:0;font-size:clamp(1rem,2.1vw,2rem);letter-spacing:-.05em}header button{border:1px solid rgba(255,255,255,.35);border-radius:8px;background:transparent;color:#fff;padding:8px 12px}
    main{max-width:1500px;margin:0 auto;padding:clamp(20px,3.5vw,54px)}.board-view{display:block}.board{display:grid;grid-template-columns:repeat(var(--columns),minmax(120px,1fr));gap:10px;padding:18px;border-radius:18px;background:#183650;box-shadow:0 26px 70px rgba(0,0,0,.25)}.category{min-height:88px;display:flex;align-items:center;justify-content:center;padding:14px;border-radius:10px;background:#376f72;color:#f4ffec;text-align:center;font-size:clamp(.8rem,1.3vw,1.2rem);font-weight:800}.category small{display:block;margin-top:7px;color:#c8e2ce;font-size:.65em;font-weight:500}.cell{min-height:clamp(78px,11vw,150px);border:1px solid var(--line);border-radius:10px;background:var(--tile);color:var(--lime);font-size:clamp(1.6rem,4vw,4.7rem);font-weight:800;transition:transform .15s,background .15s}.cell:hover,.cell:focus-visible{background:var(--lime);color:#16334d;transform:translateY(-3px)}.cell.used{background:#1b354d;border-color:#516878;color:#788b92;opacity:.66}.note{margin:16px 0 0;color:#c3d4dc;font-size:.8rem}
    .question-media{display:none;max-width:min(640px,100%);margin:2px 0 16px}.question-media.open{display:block}.question-media img{display:block;width:100%;max-width:100%;max-height:260px;object-fit:contain;border:1px solid rgba(200,241,105,.35);border-radius:10px;background:#f7fbff;padding:6px}
    .answer{display:none;max-width:900px;margin:0 0 18px;padding:14px 18px;border:2px dashed rgba(200,241,105,.75);border-radius:5px;background:repeating-linear-gradient(135deg,rgba(200,241,105,.13) 0,rgba(200,241,105,.13) 10px,rgba(0,0,0,.2) 10px,rgba(0,0,0,.2) 20px);color:#eaffdc;font-size:clamp(.9rem,1.55vw,1.5rem);line-height:1.35}.answer.open{display:block}.answer strong{display:block;margin-bottom:6px;color:var(--lime);font-size:.65em;letter-spacing:.07em}.answer small{display:block;margin-top:9px;color:#c6dcd0;font-size:.68em}.actions{display:flex;gap:10px;flex-wrap:wrap;justify-content:center}.actions button{border:0;border-radius:9px;padding:10px 15px;background:var(--lime);color:#16334d;font-weight:800}.actions button.secondary{background:transparent;border:1px solid rgba(255,255,255,.5);color:#fff}
    .scores{display:flex;justify-content:center;gap:6px;flex-wrap:wrap;padding:0 clamp(10px,2vw,32px) 8px}.team{position:relative;min-width:116px;padding:5px 7px;border-radius:7px;background:var(--paper);color:#142b40;box-shadow:0 3px 0 rgba(200,241,105,.5)}.team label{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:800;font-size:.75rem;padding-right:15px}.total{margin:3px 0;color:#183c67;font-size:clamp(1.3rem,1.9vw,2.1rem);font-weight:900;line-height:1}.team small{color:#61716b;font-size:.5rem}.team div{display:grid;grid-template-columns:1fr 1fr;gap:3px;margin-top:3px}.team button{border:0;border-radius:4px;padding:3px;background:#d8f2df;color:#22613e;font-size:.65rem;font-weight:900}.team button:last-child{background:#ffe2d8;color:#a34831}.team button:disabled{opacity:.4;cursor:not-allowed}.team .remove-team{position:absolute;top:3px;right:3px;width:14px;height:14px;padding:0;border-radius:50%;background:transparent;color:#758179;font-size:.65rem;line-height:14px}.team .remove-team:hover:not(:disabled){background:#ffe2d8;color:#a34831}
    .score-controls{display:flex;justify-content:center;align-items:center;gap:6px;padding:0 12px 5px;color:#c7d7e6;font-size:.6rem}.score-controls button{border:1px solid rgba(255,255,255,.4);border-radius:5px;padding:3px 7px;background:transparent;color:#fff;cursor:pointer}.score-controls button:disabled{opacity:.4;cursor:not-allowed}.team-name,.total-input{display:block;width:100%;border:0;background:transparent;color:#142b40;outline:none}.team-name{border-bottom:1px solid #dbe5da;font-weight:800}.total-input{margin:3px 0;color:#183c67;font-size:clamp(1.3rem,1.9vw,2.1rem);font-weight:900;line-height:1}.offline-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:4px 12px;background:#0d1c31;color:#9fb2bf;font-size:.58rem}.font-controls{display:flex;gap:4px}.font-controls button{border:1px solid rgba(255,255,255,.35);border-radius:4px;padding:2px 6px;background:transparent;color:#fff;font-size:.9em}
    .question-view{display:none;align-items:stretch;text-align:left;padding:clamp(18px,3vw,42px) clamp(20px,5vw,96px) clamp(34px,7vh,90px)}.question-view.open{display:block}.question-view .question-meta,.question-view h2,.question-view .answer,.question-view .actions{width:100%;max-width:1400px;margin-left:auto;margin-right:auto}.question-view .question-meta{text-align:left;margin-top:0}.question-view h2{max-width:1400px;margin-top:clamp(8px,1vw,18px);font-size:clamp(2.8rem,6.2vw,7.6rem);line-height:.98;letter-spacing:-.055em;text-wrap:pretty;overflow-wrap:anywhere}.question-view .question-media{max-width:900px}.question-view .answer{max-width:1400px;text-align:left}.question-view .actions{justify-content:flex-start}
    @media(max-width:720px){header{align-items:flex-start;flex-direction:column}.board{grid-template-columns:repeat(var(--columns),minmax(92px,1fr));padding:9px;overflow-x:auto}.category{min-height:70px}.cell{min-height:70px}.question-view{padding-inline:18px}.question-view h2{font-size:clamp(2.6rem,12vw,5rem)}.team{min-width:118px}}
  </style>
</head>
<body>
  <header><div><small>Offline Quiz Board · No internet required</small><h1 id="title"></h1></div><button id="reset" type="button">Restart</button></header>
  <main>
    <section class="board-view" id="board-view"><div class="board" id="board"></div><p class="note">Select a value to open a question. This file includes the full board and answers and runs offline.</p></section>
    <section class="question-view" id="question-view"><p class="question-meta" id="meta"></p><h2 id="prompt"></h2><div class="question-media" id="media-wrap"><img id="question-media" alt=""></div><div class="answer" id="answer"><strong>Correct response</strong><span id="answer-text"></span><small id="explanation"></small></div><div class="actions"><button id="reveal" type="button">Reveal answer</button><button class="secondary" id="back" type="button">Back to board</button></div></section>
  </main>
  <section class="score-controls" aria-label="Team controls"><button id="add-team" type="button">+ Add team</button><span id="team-count"></span><span id="progress"></span><button id="toggle-scores" type="button">Hide team scores</button></section><section class="scores" id="scores" aria-label="Team total scores"></section><footer class="offline-footer"><span>Totals only · details are not saved</span><div class="font-controls"><button id="font-down" type="button">A−</button><button id="font-up" type="button">A+</button><button id="hide-answer" type="button" disabled>Hide answer</button></div></footer>
  <script>
    const game = ${payload};
    const board = document.querySelector('#board'); const title = document.querySelector('#title'); const boardView = document.querySelector('#board-view'); const questionView = document.querySelector('#question-view'); const scoresEl = document.querySelector('#scores'); const mediaWrap = document.querySelector('#media-wrap'); const mediaImage = document.querySelector('#question-media');
    let active = null; let revealed = false; let scoresVisible = true; let fontScale = 1; let used = new Set(); let scores = Array.from({length: Math.max(1, Math.min(8, (game.teamNames || []).length || 2))}, function(){ return 0; }); let questionDeltas = scores.map(function(){ return 0; }); let teams = (game.teamNames || ['Team A', 'Team B']).slice(0, 8); while(teams.length < 1){ teams.push('Team A'); }
    title.textContent = game.title || game.topic || 'Offline Quiz Board'; board.style.setProperty('--columns', game.categories.length || 1);
    function renderBoard(){ board.innerHTML = ''; game.categories.forEach(function(category){ const head = document.createElement('div'); head.className = 'category'; head.innerHTML = '<div>' + text(category.name) + (category.hint ? '<small>' + text(category.hint) + '</small>' : '') + '</div>'; board.appendChild(head); }); const rows = Math.max.apply(null, game.categories.map(function(c){return c.questions.length;})); for(let row=0;row<rows;row+=1){ game.categories.forEach(function(category){ const question = category.questions[row]; if(!question){ const gap = document.createElement('div'); board.appendChild(gap); return; } const cell = document.createElement('button'); cell.type = 'button'; cell.className = 'cell' + (used.has(question.id) ? ' used' : ''); cell.textContent = question.value; cell.disabled = used.has(question.id); cell.addEventListener('click', function(){openQuestion(category, question);}); board.appendChild(cell); }); } updateProgress(); }
    function openQuestion(category, question){ active = Object.assign({category:category.name}, question); revealed = false; questionDeltas = scores.map(function(){ return 0; }); used.add(question.id); document.querySelector('#meta').textContent = active.category + ' · ' + active.value + ' points'; document.querySelector('#prompt').textContent = active.prompt; document.querySelector('#answer-text').textContent = active.answer; document.querySelector('#explanation').textContent = active.explanation || ''; if(active.media && active.media.url && active.media.url.indexOf('data:image/') === 0){ mediaImage.src = active.media.url; mediaImage.alt = active.media.alt || 'Question visual'; mediaWrap.classList.add('open'); } else { mediaImage.removeAttribute('src'); mediaImage.alt = ''; mediaWrap.classList.remove('open'); } document.querySelector('#answer').classList.remove('open'); document.querySelector('#reveal').textContent = 'Reveal answer'; document.querySelector('#hide-answer').disabled = true; boardView.style.display = 'none'; questionView.classList.add('open'); updateProgress(); renderScores(); }
    function closeQuestion(){ boardView.style.display = 'block'; questionView.classList.remove('open'); active = null; questionDeltas = scores.map(function(){ return 0; }); mediaWrap.classList.remove('open'); renderBoard(); renderScores(); }
    function renderScores(){ scoresEl.innerHTML = ''; document.querySelector('#team-count').textContent = teams.length + '/8 teams'; document.querySelector('#add-team').disabled = teams.length >= 8; teams.forEach(function(team, index){ const card = document.createElement('div'); card.className = 'team'; card.innerHTML = '<button class="remove-team" type="button" aria-label="Remove ' + text(team) + '">×</button><input class="team-name" aria-label="Team name" value="' + text(team) + '"><input class="total total-input" type="number" aria-label="Team total score" value="' + scores[index] + '"><small>Total score</small><div><button type="button">+' + (active ? active.value : 0) + '</button><button type="button">−' + (active ? active.value : 0) + '</button></div>'; const nameInput = card.querySelector('.team-name'); const totalInput = card.querySelector('.total-input'); const removeButton = card.querySelector('.remove-team'); removeButton.disabled = teams.length <= 1; removeButton.addEventListener('click', function(){ removeTeam(index); }); nameInput.addEventListener('input', function(){ teams[index] = nameInput.value; }); totalInput.addEventListener('change', function(){ updateScore(index, totalInput.value); }); const buttons = card.querySelectorAll('div button'); buttons[0].disabled = !active || !revealed; buttons[1].disabled = !active || !revealed; buttons[0].addEventListener('click', function(){adjustScore(index, active.value);}); buttons[1].addEventListener('click', function(){adjustScore(index, -active.value);}); scoresEl.appendChild(card); }); }
    function updateScore(index, value){ const next = Number(value); if(!Number.isFinite(next)) return; if(!active){ scores[index] = next; renderScores(); return; } const scoreBeforeQuestion = scores[index] - questionDeltas[index]; const nextDelta = Math.max(-active.value, Math.min(active.value, next - scoreBeforeQuestion)); questionDeltas[index] = nextDelta; scores[index] = scoreBeforeQuestion + nextDelta; renderScores(); }
    function addTeam(){ if(teams.length >= 8) return; teams.push('Team ' + String.fromCharCode(65 + teams.length)); scores.push(0); questionDeltas.push(0); renderScores(); }
    function removeTeam(index){ if(teams.length <= 1) return; teams.splice(index, 1); scores.splice(index, 1); questionDeltas.splice(index, 1); renderScores(); }
    function adjustScore(index, delta){ if(!active || !revealed) return; const next = Math.max(-active.value, Math.min(active.value, questionDeltas[index] + delta)); const applied = next - questionDeltas[index]; if(!applied) return; questionDeltas[index] = next; scores[index] += applied; renderScores(); }
    function text(value){ const div = document.createElement('div'); div.textContent = value || ''; return div.innerHTML; }
    function updateProgress(){ document.querySelector('#progress').textContent = used.size + '/' + game.categories.reduce(function(total, category){ return total + category.questions.length; }, 0) + ' questions'; }
    function setAnswerVisible(next){ revealed = next; document.querySelector('#answer').classList.toggle('open', revealed); document.querySelector('#reveal').textContent = revealed ? 'Hide answer' : 'Reveal answer'; document.querySelector('#hide-answer').disabled = !revealed; renderScores(); }
    document.querySelector('#add-team').addEventListener('click', addTeam); const toggleScores = document.querySelector('#toggle-scores'); if(toggleScores){ toggleScores.addEventListener('click', function(){ scoresVisible = !scoresVisible; scoresEl.style.display = scoresVisible ? 'flex' : 'none'; toggleScores.textContent = scoresVisible ? 'Hide team scores' : 'Show team scores'; }); } document.querySelector('#reveal').addEventListener('click', function(){ if(!active) return; setAnswerVisible(!revealed); }); document.querySelector('#hide-answer').addEventListener('click', function(){ setAnswerVisible(false); }); document.querySelector('#font-down').addEventListener('click', function(){ fontScale = Math.max(.8, Number((fontScale - .1).toFixed(1))); document.querySelector('#prompt').style.setProperty('--font-scale', fontScale); }); document.querySelector('#font-up').addEventListener('click', function(){ fontScale = Math.min(1.2, Number((fontScale + .1).toFixed(1))); document.querySelector('#prompt').style.setProperty('--font-scale', fontScale); }); document.querySelector('#back').addEventListener('click', closeQuestion); document.querySelector('#reset').addEventListener('click', function(){ active = null; setAnswerVisible(false); used = new Set(); scores = teams.map(function(){ return 0; }); questionDeltas = scores.map(function(){ return 0; }); boardView.style.display = 'block'; questionView.classList.remove('open'); renderBoard(); renderScores(); }); document.addEventListener('keydown', function(event){ if(event.key === 'Escape' && active) closeQuestion(); if(event.key === ' ' && active){ event.preventDefault(); document.querySelector('#reveal').click(); } });
    renderBoard(); renderScores();
    if (game.categories[0] && game.categories[0].questions[0]) {
      window.setTimeout(function(){ openQuestion(game.categories[0], game.categories[0].questions[0]); }, 0);
    }
  <\/script>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character] || character);
}
